/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SelectProfileRouteImport } from './routes/select-profile'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MinervaIndexRouteImport } from './routes/minerva.index'
import { Route as JanoIndexRouteImport } from './routes/jano.index'
import { Route as JanoReaderRouteImport } from './routes/jano.reader'

const SelectProfileRoute = SelectProfileRouteImport.update({
  id: '/select-profile',
  path: '/select-profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MinervaIndexRoute = MinervaIndexRouteImport.update({
  id: '/minerva/',
  path: '/minerva/',
  getParentRoute: () => rootRouteImport,
} as any)
const JanoIndexRoute = JanoIndexRouteImport.update({
  id: '/jano/',
  path: '/jano/',
  getParentRoute: () => rootRouteImport,
} as any)
const JanoReaderRoute = JanoReaderRouteImport.update({
  id: '/jano/reader',
  path: '/jano/reader',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/select-profile': typeof SelectProfileRoute
  '/jano/reader': typeof JanoReaderRoute
  '/jano/': typeof JanoIndexRoute
  '/minerva/': typeof MinervaIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/select-profile': typeof SelectProfileRoute
  '/jano/reader': typeof JanoReaderRoute
  '/jano': typeof JanoIndexRoute
  '/minerva': typeof MinervaIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/select-profile': typeof SelectProfileRoute
  '/jano/reader': typeof JanoReaderRoute
  '/jano/': typeof JanoIndexRoute
  '/minerva/': typeof MinervaIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/select-profile'
    | '/jano/reader'
    | '/jano/'
    | '/minerva/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/select-profile' | '/jano/reader' | '/jano' | '/minerva'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/select-profile'
    | '/jano/reader'
    | '/jano/'
    | '/minerva/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  SelectProfileRoute: typeof SelectProfileRoute
  JanoReaderRoute: typeof JanoReaderRoute
  JanoIndexRoute: typeof JanoIndexRoute
  MinervaIndexRoute: typeof MinervaIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/select-profile': {
      id: '/select-profile'
      path: '/select-profile'
      fullPath: '/select-profile'
      preLoaderRoute: typeof SelectProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/minerva/': {
      id: '/minerva/'
      path: '/minerva'
      fullPath: '/minerva/'
      preLoaderRoute: typeof MinervaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jano/': {
      id: '/jano/'
      path: '/jano'
      fullPath: '/jano/'
      preLoaderRoute: typeof JanoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jano/reader': {
      id: '/jano/reader'
      path: '/jano/reader'
      fullPath: '/jano/reader'
      preLoaderRoute: typeof JanoReaderRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  SelectProfileRoute: SelectProfileRoute,
  JanoReaderRoute: JanoReaderRoute,
  JanoIndexRoute: JanoIndexRoute,
  MinervaIndexRoute: MinervaIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
