/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AvatarRouteImport } from './routes/avatar'
import { Route as LoadingRouteImport } from './routes/loading'
import { Route as SelectProfileRouteImport } from './routes/select-profile'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogSubmitRouteImport } from './routes/blog.submit'
import { Route as JanoIndexRouteImport } from './routes/jano.index'
import { Route as JanoArticlesRouteImport } from './routes/jano.articles'
import { Route as JanoImportRouteImport } from './routes/jano.import'
import { Route as JanoReaderRouteImport } from './routes/jano.reader'
import { Route as MinervaIndexRouteImport } from './routes/minerva.index'
import { Route as MinervaConversaRouteImport } from './routes/minerva.conversa'
import { Route as BlogArticleSlugRouteImport } from './routes/blog.article.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AvatarRoute = AvatarRouteImport.update({
  id: '/avatar',
  path: '/avatar',
  getParentRoute: () => rootRouteImport,
} as any)
const LoadingRoute = LoadingRouteImport.update({
  id: '/loading',
  path: '/loading',
  getParentRoute: () => rootRouteImport,
} as any)
const SelectProfileRoute = SelectProfileRouteImport.update({
  id: '/select-profile',
  path: '/select-profile',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSubmitRoute = BlogSubmitRouteImport.update({
  id: '/blog/submit',
  path: '/blog/submit',
  getParentRoute: () => rootRouteImport,
} as any)
const JanoIndexRoute = JanoIndexRouteImport.update({
  id: '/jano/',
  path: '/jano/',
  getParentRoute: () => rootRouteImport,
} as any)
const JanoArticlesRoute = JanoArticlesRouteImport.update({
  id: '/jano/articles',
  path: '/jano/articles',
  getParentRoute: () => rootRouteImport,
} as any)
const JanoImportRoute = JanoImportRouteImport.update({
  id: '/jano/import',
  path: '/jano/import',
  getParentRoute: () => rootRouteImport,
} as any)
const JanoReaderRoute = JanoReaderRouteImport.update({
  id: '/jano/reader',
  path: '/jano/reader',
  getParentRoute: () => rootRouteImport,
} as any)
const MinervaIndexRoute = MinervaIndexRouteImport.update({
  id: '/minerva/',
  path: '/minerva/',
  getParentRoute: () => rootRouteImport,
} as any)
const MinervaConversaRoute = MinervaConversaRouteImport.update({
  id: '/minerva/conversa',
  path: '/minerva/conversa',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogArticleSlugRoute = BlogArticleSlugRouteImport.update({
  id: '/blog/article/$slug',
  path: '/blog/article/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/avatar': typeof AvatarRoute
  '/loading': typeof LoadingRoute
  '/select-profile': typeof SelectProfileRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/blog/submit': typeof BlogSubmitRoute
  '/jano/articles': typeof JanoArticlesRoute
  '/jano/import': typeof JanoImportRoute
  '/jano/reader': typeof JanoReaderRoute
  '/minerva/conversa': typeof MinervaConversaRoute
  '/blog/': typeof BlogIndexRoute
  '/jano/': typeof JanoIndexRoute
  '/minerva/': typeof MinervaIndexRoute
  '/blog/article/$slug': typeof BlogArticleSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/avatar': typeof AvatarRoute
  '/loading': typeof LoadingRoute
  '/select-profile': typeof SelectProfileRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/blog/submit': typeof BlogSubmitRoute
  '/jano/articles': typeof JanoArticlesRoute
  '/jano/import': typeof JanoImportRoute
  '/jano/reader': typeof JanoReaderRoute
  '/minerva/conversa': typeof MinervaConversaRoute
  '/blog': typeof BlogIndexRoute
  '/jano': typeof JanoIndexRoute
  '/minerva': typeof MinervaIndexRoute
  '/blog/article/$slug': typeof BlogArticleSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/avatar': typeof AvatarRoute
  '/loading': typeof LoadingRoute
  '/select-profile': typeof SelectProfileRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/blog/submit': typeof BlogSubmitRoute
  '/jano/articles': typeof JanoArticlesRoute
  '/jano/import': typeof JanoImportRoute
  '/jano/reader': typeof JanoReaderRoute
  '/minerva/conversa': typeof MinervaConversaRoute
  '/blog/': typeof BlogIndexRoute
  '/jano/': typeof JanoIndexRoute
  '/minerva/': typeof MinervaIndexRoute
  '/blog/article/$slug': typeof BlogArticleSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/avatar'
    | '/loading'
    | '/select-profile'
    | '/settings'
    | '/sitemap.xml'
    | '/blog/submit'
    | '/jano/articles'
    | '/jano/import'
    | '/jano/reader'
    | '/minerva/conversa'
    | '/blog/'
    | '/jano/'
    | '/minerva/'
    | '/blog/article/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/avatar'
    | '/loading'
    | '/select-profile'
    | '/settings'
    | '/sitemap.xml'
    | '/blog/submit'
    | '/jano/articles'
    | '/jano/import'
    | '/jano/reader'
    | '/minerva/conversa'
    | '/blog'
    | '/jano'
    | '/minerva'
    | '/blog/article/$slug'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/avatar'
    | '/loading'
    | '/select-profile'
    | '/settings'
    | '/sitemap.xml'
    | '/blog/submit'
    | '/jano/articles'
    | '/jano/import'
    | '/jano/reader'
    | '/minerva/conversa'
    | '/blog/'
    | '/jano/'
    | '/minerva/'
    | '/blog/article/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  AvatarRoute: typeof AvatarRoute
  LoadingRoute: typeof LoadingRoute
  SelectProfileRoute: typeof SelectProfileRoute
  SettingsRoute: typeof SettingsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  BlogSubmitRoute: typeof BlogSubmitRoute
  JanoArticlesRoute: typeof JanoArticlesRoute
  JanoImportRoute: typeof JanoImportRoute
  JanoReaderRoute: typeof JanoReaderRoute
  MinervaConversaRoute: typeof MinervaConversaRoute
  BlogIndexRoute: typeof BlogIndexRoute
  JanoIndexRoute: typeof JanoIndexRoute
  MinervaIndexRoute: typeof MinervaIndexRoute
  BlogArticleSlugRoute: typeof BlogArticleSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/avatar': {
      id: '/avatar'
      path: '/avatar'
      fullPath: '/avatar'
      preLoaderRoute: typeof AvatarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loading': {
      id: '/loading'
      path: '/loading'
      fullPath: '/loading'
      preLoaderRoute: typeof LoadingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/select-profile': {
      id: '/select-profile'
      path: '/select-profile'
      fullPath: '/select-profile'
      preLoaderRoute: typeof SelectProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/submit': {
      id: '/blog/submit'
      path: '/blog/submit'
      fullPath: '/blog/submit'
      preLoaderRoute: typeof BlogSubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jano/': {
      id: '/jano/'
      path: '/jano'
      fullPath: '/jano/'
      preLoaderRoute: typeof JanoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jano/articles': {
      id: '/jano/articles'
      path: '/jano/articles'
      fullPath: '/jano/articles'
      preLoaderRoute: typeof JanoArticlesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jano/import': {
      id: '/jano/import'
      path: '/jano/import'
      fullPath: '/jano/import'
      preLoaderRoute: typeof JanoImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jano/reader': {
      id: '/jano/reader'
      path: '/jano/reader'
      fullPath: '/jano/reader'
      preLoaderRoute: typeof JanoReaderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/minerva/': {
      id: '/minerva/'
      path: '/minerva'
      fullPath: '/minerva/'
      preLoaderRoute: typeof MinervaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/minerva/conversa': {
      id: '/minerva/conversa'
      path: '/minerva/conversa'
      fullPath: '/minerva/conversa'
      preLoaderRoute: typeof MinervaConversaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/article/$slug': {
      id: '/blog/article/$slug'
      path: '/blog/article/$slug'
      fullPath: '/blog/article/$slug'
      preLoaderRoute: typeof BlogArticleSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  AvatarRoute: AvatarRoute,
  LoadingRoute: LoadingRoute,
  SelectProfileRoute: SelectProfileRoute,
  SettingsRoute: SettingsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  BlogSubmitRoute: BlogSubmitRoute,
  JanoArticlesRoute: JanoArticlesRoute,
  JanoImportRoute: JanoImportRoute,
  JanoReaderRoute: JanoReaderRoute,
  MinervaConversaRoute: MinervaConversaRoute,
  BlogIndexRoute: BlogIndexRoute,
  JanoIndexRoute: JanoIndexRoute,
  MinervaIndexRoute: MinervaIndexRoute,
  BlogArticleSlugRoute: BlogArticleSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
